In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('ESSdata_Thinkful.csv')

In [3]:
df.head()

,cntry,idno,year,tvtot,ppltrst,pplfair,pplhlp,happy,sclmeet,sclact,gndr,agea,partner
0,CH,5.0,6,3.0,3.0,10.0,5.0,8.0,5.0,4.0,2.0,60.0,1.0
1,CH,25.0,6,6.0,5.0,7.0,5.0,9.0,3.0,2.0,2.0,59.0,1.0
2,CH,26.0,6,1.0,8.0,8.0,8.0,7.0,6.0,3.0,1.0,24.0,2.0
3,CH,28.0,6,4.0,6.0,6.0,7.0,10.0,6.0,2.0,2.0,64.0,1.0
4,CH,29.0,6,5.0,6.0,7.0,5.0,8.0,7.0,2.0,2.0,55.0,1.0

In [4]:
df.cntry.unique()

array(['CH', 'CZ', 'DE', 'ES', 'NO', 'SE'], dtype=object)

In [5]:
df.dtypes

cntry       object
idno       float64
year         int64
tvtot      float64
ppltrst    float64
pplfair    float64
pplhlp     float64
happy      float64
sclmeet    float64
sclact     float64
gndr       float64
agea       float64
partner    float64
dtype: object

In [6]:
type(df.year)

pandas.core.series.Series

In [7]:
#Categorize each of the variables in the ESS dataset as categorical or continuous, 
#and if continuous as ordinal, interval, or ratio variables. Check your work with your mentor, 
#and discuss what that information might imply for feature engineering with this data.

In [8]:
df['Nordic'] = np.where((df['cntry'].isin(['NO', 'SE'])), 1, 0)
print(pd.crosstab(df['Nordic'], df['cntry']))

cntry     CH    CZ  DE    ES    NO    SE
Nordic
0       1546  1316  28  2426     0     0
1          0     0   0     0  1462  1816

In [9]:
#df['Nordic'] = np.where((df['cntry'].isin(['NO', 'SE'])), 1, 0)

In [10]:
df['idno'] = pd.cut(df.idno,[0,10], include_lowest = True)
print(df)

     cntry            idno  year  tvtot  ppltrst  pplfair  pplhlp  happy  \
0       CH  (-0.001, 10.0]     6    3.0      3.0     10.0     5.0    8.0
1       CH             NaN     6    6.0      5.0      7.0     5.0    9.0
2       CH             NaN     6    1.0      8.0      8.0     8.0    7.0
3       CH             NaN     6    4.0      6.0      6.0     7.0   10.0
4       CH             NaN     6    5.0      6.0      7.0     5.0    8.0
5       CH             NaN     6    4.0      6.0      7.0     3.0    8.0
6       CH             NaN     6    3.0      0.0      5.0     2.0    0.0
7       CH             NaN     6    2.0      4.0      5.0     3.0   10.0
8       CH             NaN     6    2.0      8.0      8.0     8.0    9.0
9       CH             NaN     6    4.0      4.0      4.0     8.0    7.0
10      CH             NaN     6    1.0      6.0      7.0     7.0    9.0
11      CH             NaN     6    4.0      5.0      7.0     7.0    7.0
12      CH             NaN     6    4.0      7.0      7.0     4.0    9.0
13      CH             NaN     6    2.0      1.0      9.0     7.0    8.0
14      CH             NaN     6    4.0      4.0      5.0     3.0    8.0
15      CH             NaN     6    5.0      4.0      5.0     5.0    9.0
16      CH             NaN     6    4.0      5.0      7.0     7.0    8.0
17      CH             NaN     6    2.0      7.0      7.0     7.0    6.0
18      CH             NaN     6    0.0      9.0      7.0     8.0    9.0
19      CH             NaN     6    2.0      6.0      6.0     6.0    8.0
20      CH             NaN     6    7.0      3.0      4.0     4.0    7.0
21      CH             NaN     6    1.0      8.0      8.0     6.0    8.0
22      CH             NaN     6    2.0      7.0      7.0     8.0    9.0
23      CH             NaN     6    2.0      4.0      8.0     8.0    9.0
24      CH             NaN     6    0.0      7.0      7.0     4.0    9.0
25      CH             NaN     6    0.0      6.0      7.0     5.0    7.0
26      CH             NaN     6    2.0      7.0      6.0     5.0    8.0
27      CH             NaN     6    0.0      5.0      8.0     6.0    9.0
28      CH             NaN     6    2.0      8.0      8.0     8.0   10.0
29      CH             NaN     6    7.0      8.0      5.0     5.0    8.0
...    ...             ...   ...    ...      ...      ...     ...    ...
8564    SE             NaN     7    2.0      1.0      5.0     4.0   10.0
8565    SE             NaN     7    5.0      5.0      3.0     4.0    5.0
8566    SE             NaN     7    2.0      7.0      8.0     6.0    8.0
8567    SE             NaN     7    2.0      4.0      8.0     7.0    9.0
8568    SE             NaN     7    1.0      2.0      8.0     6.0    9.0
8569    SE             NaN     7    6.0      5.0      3.0     4.0    9.0
8570    SE             NaN     7    1.0      5.0      7.0     7.0    8.0
8571    SE             NaN     7    3.0      4.0      9.0     7.0    8.0
8572    SE             NaN     7    5.0      7.0      8.0     5.0    8.0
8573    SE             NaN     7    1.0      8.0      8.0     6.0    9.0
8574    SE             NaN     7    1.0      4.0      5.0     6.0    7.0
8575    SE             NaN     7    3.0      8.0      7.0     7.0    8.0
8576    SE             NaN     7    4.0      5.0      4.0     4.0    7.0
8577    SE             NaN     7    6.0      6.0      9.0     7.0    5.0
8578    SE             NaN     7    1.0      5.0      5.0     5.0    7.0
8579    SE             NaN     7    2.0      8.0      9.0     7.0    9.0
8580    SE             NaN     7    4.0      7.0      8.0     5.0   10.0
8581    SE             NaN     7    1.0      6.0      7.0     6.0    8.0
8582    SE             NaN     7    6.0      7.0      7.0     6.0    8.0
8583    SE             NaN     7    2.0      6.0      8.0     5.0   10.0
8584    SE             NaN     7    2.0      8.0     10.0     6.0    9.0
8585    SE             NaN     7    1.0      3.0      6.0     4.0    9.0
8586    SE             NaN     7    2.0      4.0      6.0     3.0    7.0
8587    SE             NaN     7    4.0      4.0      6.0     7.0    9.0
8588    SE             NaN     7    1.0      6.0      5.0     5.0   10.0
8589    SE             NaN     7    3.0      4.0      5.0     3.0    6.0
8590    SE             NaN     7    5.0      6.0      4.0     4.0   10.0
8591    SE             NaN     7    4.0      5.0      7.0     6.0    8.0
8592    SE             NaN     7    5.0      8.0      8.0     6.0    9.0
8593    SE             NaN     7    2.0      6.0      7.0     5.0    7.0

      sclmeet  sclact  gndr  agea  partner  Nordic
0         5.0     4.0   2.0  60.0      1.0       0
1         3.0     2.0   2.0  59.0      1.0       0
2         6.0     3.0   1.0  24.0      2.0       0
3         6.0     2.0   2.0  64.0      1.0       0
4         7.0     2.0   2.0  55.0      1.0       0
5         7.0     4.0   2.0   NaN      2.0       0
6         2.0     2.0   1.0  76.0      1.0       0
7         5.0     2.0   2.0  30.0      1.0       0
8         6.0     4.0   2.0  84.0      2.0       0
9         4.0     2.0   2.0  62.0      1.0       0
10        5.0     2.0   2.0  33.0      1.0       0
11        5.0     3.0   1.0  40.0      1.0       0
12        6.0     2.0   1.0  69.0      1.0       0
13        4.0     3.0   1.0  59.0      2.0       0
14        1.0     2.0   2.0  32.0      1.0       0
15        3.0     3.0   2.0  70.0      1.0       0
16        3.0     3.0   1.0  61.0      1.0       0
17        6.0     3.0   1.0  30.0      1.0       0
18        5.0     4.0   1.0  21.0      2.0       0
19        4.0     3.0   2.0  36.0      1.0       0
20        6.0     4.0   1.0  51.0      1.0       0
21        7.0     4.0   1.0  25.0      2.0       0
22        6.0     3.0   1.0  62.0      1.0       0
23        6.0     2.0   2.0  20.0      2.0       0
24        4.0     2.0   2.0  22.0      1.0       0
25        6.0     2.0   2.0  32.0      1.0       0
26        4.0     3.0   2.0  35.0      1.0       0
27        4.0     2.0   2.0  26.0      1.0       0
28        6.0     3.0   2.0  35.0      1.0       0
29        5.0     3.0   2.0  54.0      1.0       0
...       ...     ...   ...   ...      ...     ...
8564      7.0     4.0   1.0  17.0      2.0       1
8565      6.0     1.0   2.0  17.0      2.0       1
8566      7.0     3.0   2.0  17.0      2.0       1
8567      7.0     4.0   2.0  17.0      2.0       1
8568      7.0     3.0   2.0  17.0      2.0       1
8569      6.0     4.0   1.0  17.0      2.0       1
8570      7.0     4.0   1.0  16.0      2.0       1
8571      6.0     3.0   1.0  16.0      2.0       1
8572      3.0     1.0   1.0  16.0      2.0       1
8573      7.0     3.0   2.0  16.0      2.0       1
8574      7.0     3.0   2.0  16.0      2.0       1
8575      7.0     3.0   1.0  16.0      2.0       1
8576      6.0     3.0   1.0  16.0      2.0       1
8577      4.0     2.0   2.0  16.0      2.0       1
8578      5.0     4.0   2.0  16.0      2.0       1
8579      7.0     3.0   2.0  16.0      2.0       1
8580      4.0     1.0   1.0  16.0      2.0       1
8581      6.0     3.0   1.0  16.0      2.0       1
8582      7.0     3.0   1.0  16.0      2.0       1
8583      6.0     5.0   1.0  16.0      2.0       1
8584      6.0     2.0   1.0  16.0      2.0       1
8585      7.0     3.0   1.0  16.0      2.0       1
8586      7.0     3.0   2.0  15.0      2.0       1
8587      7.0     3.0   1.0  15.0      2.0       1
8588      7.0     2.0   1.0  15.0      2.0       1
8589      6.0     2.0   1.0  18.0      2.0       1
8590      6.0     3.0   1.0  15.0      2.0       1
8591      6.0     3.0   1.0  44.0      2.0       1
8592      7.0     3.0   1.0  15.0      2.0       1
8593      7.0     4.0   2.0  15.0      2.0       1

[8594 rows x 14 columns]

In [11]:
df['year'] = pd.cut(df.year,[6,7], include_lowest = True)
print(df)

     cntry            idno          year  tvtot  ppltrst  pplfair  pplhlp  \
0       CH  (-0.001, 10.0]  (5.999, 7.0]    3.0      3.0     10.0     5.0
1       CH             NaN  (5.999, 7.0]    6.0      5.0      7.0     5.0
2       CH             NaN  (5.999, 7.0]    1.0      8.0      8.0     8.0
3       CH             NaN  (5.999, 7.0]    4.0      6.0      6.0     7.0
4       CH             NaN  (5.999, 7.0]    5.0      6.0      7.0     5.0
5       CH             NaN  (5.999, 7.0]    4.0      6.0      7.0     3.0
6       CH             NaN  (5.999, 7.0]    3.0      0.0      5.0     2.0
7       CH             NaN  (5.999, 7.0]    2.0      4.0      5.0     3.0
8       CH             NaN  (5.999, 7.0]    2.0      8.0      8.0     8.0
9       CH             NaN  (5.999, 7.0]    4.0      4.0      4.0     8.0
10      CH             NaN  (5.999, 7.0]    1.0      6.0      7.0     7.0
11      CH             NaN  (5.999, 7.0]    4.0      5.0      7.0     7.0
12      CH             NaN  (5.999, 7.0]    4.0      7.0      7.0     4.0
13      CH             NaN  (5.999, 7.0]    2.0      1.0      9.0     7.0
14      CH             NaN  (5.999, 7.0]    4.0      4.0      5.0     3.0
15      CH             NaN  (5.999, 7.0]    5.0      4.0      5.0     5.0
16      CH             NaN  (5.999, 7.0]    4.0      5.0      7.0     7.0
17      CH             NaN  (5.999, 7.0]    2.0      7.0      7.0     7.0
18      CH             NaN  (5.999, 7.0]    0.0      9.0      7.0     8.0
19      CH             NaN  (5.999, 7.0]    2.0      6.0      6.0     6.0
20      CH             NaN  (5.999, 7.0]    7.0      3.0      4.0     4.0
21      CH             NaN  (5.999, 7.0]    1.0      8.0      8.0     6.0
22      CH             NaN  (5.999, 7.0]    2.0      7.0      7.0     8.0
23      CH             NaN  (5.999, 7.0]    2.0      4.0      8.0     8.0
24      CH             NaN  (5.999, 7.0]    0.0      7.0      7.0     4.0
25      CH             NaN  (5.999, 7.0]    0.0      6.0      7.0     5.0
26      CH             NaN  (5.999, 7.0]    2.0      7.0      6.0     5.0
27      CH             NaN  (5.999, 7.0]    0.0      5.0      8.0     6.0
28      CH             NaN  (5.999, 7.0]    2.0      8.0      8.0     8.0
29      CH             NaN  (5.999, 7.0]    7.0      8.0      5.0     5.0
...    ...             ...           ...    ...      ...      ...     ...
8564    SE             NaN  (5.999, 7.0]    2.0      1.0      5.0     4.0
8565    SE             NaN  (5.999, 7.0]    5.0      5.0      3.0     4.0
8566    SE             NaN  (5.999, 7.0]    2.0      7.0      8.0     6.0
8567    SE             NaN  (5.999, 7.0]    2.0      4.0      8.0     7.0
8568    SE             NaN  (5.999, 7.0]    1.0      2.0      8.0     6.0
8569    SE             NaN  (5.999, 7.0]    6.0      5.0      3.0     4.0
8570    SE             NaN  (5.999, 7.0]    1.0      5.0      7.0     7.0
8571    SE             NaN  (5.999, 7.0]    3.0      4.0      9.0     7.0
8572    SE             NaN  (5.999, 7.0]    5.0      7.0      8.0     5.0
8573    SE             NaN  (5.999, 7.0]    1.0      8.0      8.0     6.0
8574    SE             NaN  (5.999, 7.0]    1.0      4.0      5.0     6.0
8575    SE             NaN  (5.999, 7.0]    3.0      8.0      7.0     7.0
8576    SE             NaN  (5.999, 7.0]    4.0      5.0      4.0     4.0
8577    SE             NaN  (5.999, 7.0]    6.0      6.0      9.0     7.0
8578    SE             NaN  (5.999, 7.0]    1.0      5.0      5.0     5.0
8579    SE             NaN  (5.999, 7.0]    2.0      8.0      9.0     7.0
8580    SE             NaN  (5.999, 7.0]    4.0      7.0      8.0     5.0
8581    SE             NaN  (5.999, 7.0]    1.0      6.0      7.0     6.0
8582    SE             NaN  (5.999, 7.0]    6.0      7.0      7.0     6.0
8583    SE             NaN  (5.999, 7.0]    2.0      6.0      8.0     5.0
8584    SE             NaN  (5.999, 7.0]    2.0      8.0     10.0     6.0
8585    SE             NaN  (5.999, 7.0]    1.0      3.0      6.0     4.0
8586    SE             NaN  (5.999, 7.0]    2.0      4.0      6.0     3.0
8587    SE             NaN  (5.999, 7.0]    4.0      4.0      6.0     7.0
8588    SE             NaN  (5.999, 7.0]    1.0      6.0      5.0     5.0
8589    SE             NaN  (5.999, 7.0]    3.0      4.0      5.0     3.0
8590    SE             NaN  (5.999, 7.0]    5.0      6.0      4.0     4.0
8591    SE             NaN  (5.999, 7.0]    4.0      5.0      7.0     6.0
8592    SE             NaN  (5.999, 7.0]    5.0      8.0      8.0     6.0
8593    SE             NaN  (5.999, 7.0]    2.0      6.0      7.0     5.0

      happy  sclmeet  sclact  gndr  agea  partner  Nordic
0       8.0      5.0     4.0   2.0  60.0      1.0       0
1       9.0      3.0     2.0   2.0  59.0      1.0       0
2       7.0      6.0     3.0   1.0  24.0      2.0       0
3      10.0      6.0     2.0   2.0  64.0      1.0       0
4       8.0      7.0     2.0   2.0  55.0      1.0       0
5       8.0      7.0     4.0   2.0   NaN      2.0       0
6       0.0      2.0     2.0   1.0  76.0      1.0       0
7      10.0      5.0     2.0   2.0  30.0      1.0       0
8       9.0      6.0     4.0   2.0  84.0      2.0       0
9       7.0      4.0     2.0   2.0  62.0      1.0       0
10      9.0      5.0     2.0   2.0  33.0      1.0       0
11      7.0      5.0     3.0   1.0  40.0      1.0       0
12      9.0      6.0     2.0   1.0  69.0      1.0       0
13      8.0      4.0     3.0   1.0  59.0      2.0       0
14      8.0      1.0     2.0   2.0  32.0      1.0       0
15      9.0      3.0     3.0   2.0  70.0      1.0       0
16      8.0      3.0     3.0   1.0  61.0      1.0       0
17      6.0      6.0     3.0   1.0  30.0      1.0       0
18      9.0      5.0     4.0   1.0  21.0      2.0       0
19      8.0      4.0     3.0   2.0  36.0      1.0       0
20      7.0      6.0     4.0   1.0  51.0      1.0       0
21      8.0      7.0     4.0   1.0  25.0      2.0       0
22      9.0      6.0     3.0   1.0  62.0      1.0       0
23      9.0      6.0     2.0   2.0  20.0      2.0       0
24      9.0      4.0     2.0   2.0  22.0      1.0       0
25      7.0      6.0     2.0   2.0  32.0      1.0       0
26      8.0      4.0     3.0   2.0  35.0      1.0       0
27      9.0      4.0     2.0   2.0  26.0      1.0       0
28     10.0      6.0     3.0   2.0  35.0      1.0       0
29      8.0      5.0     3.0   2.0  54.0      1.0       0
...     ...      ...     ...   ...   ...      ...     ...
8564   10.0      7.0     4.0   1.0  17.0      2.0       1
8565    5.0      6.0     1.0   2.0  17.0      2.0       1
8566    8.0      7.0     3.0   2.0  17.0      2.0       1
8567    9.0      7.0     4.0   2.0  17.0      2.0       1
8568    9.0      7.0     3.0   2.0  17.0      2.0       1
8569    9.0      6.0     4.0   1.0  17.0      2.0       1
8570    8.0      7.0     4.0   1.0  16.0      2.0       1
8571    8.0      6.0     3.0   1.0  16.0      2.0       1
8572    8.0      3.0     1.0   1.0  16.0      2.0       1
8573    9.0      7.0     3.0   2.0  16.0      2.0       1
8574    7.0      7.0     3.0   2.0  16.0      2.0       1
8575    8.0      7.0     3.0   1.0  16.0      2.0       1
8576    7.0      6.0     3.0   1.0  16.0      2.0       1
8577    5.0      4.0     2.0   2.0  16.0      2.0       1
8578    7.0      5.0     4.0   2.0  16.0      2.0       1
8579    9.0      7.0     3.0   2.0  16.0      2.0       1
8580   10.0      4.0     1.0   1.0  16.0      2.0       1
8581    8.0      6.0     3.0   1.0  16.0      2.0       1
8582    8.0      7.0     3.0   1.0  16.0      2.0       1
8583   10.0      6.0     5.0   1.0  16.0      2.0       1
8584    9.0      6.0     2.0   1.0  16.0      2.0       1
8585    9.0      7.0     3.0   1.0  16.0      2.0       1
8586    7.0      7.0     3.0   2.0  15.0      2.0       1
8587    9.0      7.0     3.0   1.0  15.0      2.0       1
8588   10.0      7.0     2.0   1.0  15.0      2.0       1
8589    6.0      6.0     2.0   1.0  18.0      2.0       1
8590   10.0      6.0     3.0   1.0  15.0      2.0       1
8591    8.0      6.0     3.0   1.0  44.0      2.0       1
8592    9.0      7.0     3.0   1.0  15.0      2.0       1
8593    7.0      7.0     4.0   2.0  15.0      2.0       1

[8594 rows x 14 columns]